config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  devise_for :users
  root to: 'home#top' 
  resources :questions, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '一般常識' },
    { id: 3, name: 'ビジネスマナー' },
    { id: 4, name: 'IT' },
    { id: 5, name: '看護' }
  ]

  include ActiveHash::Associations
  has_many :question_frames
  
  end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question

end

app/models/company.rb
class Company < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '株式会社●●ホールディングス' },
    { id: 3, name: '株式会社▲▲' },
    { id: 4, name: '株式会社■■' },
    { id: 5, name: '株式会社◆◆' }
  ]

  include ActiveHash::Associations
  has_many :users

  end

app/models/division.rb
class Division < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '本部' },
    { id: 3, name: '看護部' },
    { id: 4, name: '事務局' }
  ]

  include ActiveHash::Associations
  has_many :users
  
  end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :question_frame
  has_many :choices

end

app/models/question_frame.rb
class QuestionFrame < ApplicationRecord
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

end

app/models/station.rb
class Station < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '柏ステーション' },
    { id: 3, name: '松戸ステーション' },
    { id: 4, name: '千葉ステーション' },
    { id: 5, name: '成田ステーション' },
    { id: 6, name: '流山ステーション' }
  ]

  include ActiveHash::Associations
  has_many :users
  
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :family_name, presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
  validates :family_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, length: { minimum: 6 }, format: { with: VALID_PASSWORD_REGEX }
  validates :company_id, numericality: { other_than: 1 , message: "can't be blank"} 
  validates :division_id, numericality: { other_than: 1 , message: "can't be blank"} 

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :company
  belongs_to :division
  belongs_to :station
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :first_name, :family_name_kana, :first_name_kana, :company_id, :division_id, :station_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: :top

  def top
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/top.html.erb
<%= render "shared/header" %>

<h1>Home#top</h1>
<p>Find me in app/views/home/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E-Learning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/new.html.erb
<%= render "shared/header" %>

<h1> 問題作成ページ </h1>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class="p-3 mb-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a class="navbar-brand me-5" href="#">
        <img src="logo.png" alt="e-learning" width="150" height="40">
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><%= link_to '問題一覧', '/', class: "nav-link px-2 link-secondary" %></li>
        <li><%= link_to '問題作成', new_question_path, class: "nav-link px-2 link-secondary" %></li>
        <li><%= link_to '利用者管理', '#', class: "nav-link px-2 link-secondary" %></li>
      </ul>

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
      </form>

      <div class="dropdown text-end">
        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
        </a>
        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
          <li><a class="dropdown-item" href="#">Profile</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-footer'>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo.png", class:"second-logo"), "/" %>
</header>